spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: thinguyen01683@gmail.com
    password: qcintvqlwpgdwzdo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
